version: '3'
services:
  backend-app:
    build: ./backend-app
    container_name: backend_app
    ports:
      - "8083:8081"
    volumes:
      - ./env.js:/app/env.js
    restart: always

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice_server
    ports:
      - "8082:80"
    environment:
      # Tắt JWT đi để anh dễ test trên Localhost không bị lỗi chặn Token
      - JWT_ENABLED=false
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend-app
      - onlyoffice
    restart: always
