services:
  backend-app:
    build: ./backend-app
    container_name: backend_app
    env_file:
      - ./backend-app/.env
    ports:
      - "8083:8081"
    volumes:
      - ./env.js:/app/env.js
    restart: always

  onlyoffice:
    image: onlyoffice/documentserver:9.3.1.2
    container_name: onlyoffice_server
    ports:
      - "8082:80"
    environment:
      # Tắt JWT đi để anh dễ test trên Localhost không bị lỗi chặn Token
      - JWT_ENABLED=false
      # Cho phép Document Server gọi backend local qua host.docker.internal.
      - ALLOW_PRIVATE_IP_ADDRESS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend-app
      - onlyoffice
    restart: always
