CREATE TABLE [dbo].[tbNhaphang](
    [DocumentID] [varchar](50) NOT NULL,
    [DocumentDate] [datetime] NULL,
    [Phieunhap] [varchar](50) NULL,
    [Ngaynhap] [datetime] NULL,
    [Mancc] [varchar](50) NULL,
    [Manv] [varchar](50) NULL,
    [Tongtienhoadon] [decimal](18, 0) NULL,
    [Tongtien] [decimal](18, 0) NULL,
    [Nodau] [decimal](18, 0) NULL,
    [Thanhtoan] [decimal](18, 0) NULL,
    [Conno] [decimal](18, 0) NULL,
    [Ghichu] [nvarchar](500) NULL,
    [Donkinh] [varchar](50) NULL,
    [UserCreate] [varchar](50) NULL,
    [UserUpdate] [varchar](50) NULL,
    [DateCreate] [datetime] NULL,
    [DateUpdate] [datetime] NULL,
    [Nhahangid] [varchar](50) NULL,
    [Loainhapxuatid] [varchar](50) NULL,
    [Soctu] [varchar](50) NULL,
    [Nguoigiaohang] [nvarchar](255) NULL,
    [IsNhapxuatthang] [bit] NULL,
    [Sophieuyeucau] [varchar](50) NULL,
    [IsPhatsinh] [bit] NULL,
 CONSTRAINT [PK_tbNhaphang] PRIMARY KEY CLUSTERED ([DocumentID] ASC)
)
